name: CI

on: [push]
  
jobs:
  test_build_run_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        run: |
          sudo apt-get install terraform
          terraform --version
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_PASSWORD }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_USERNAME }}
      - name: run main.tf
        run: |
          terraform init --auto-approve
          terraform apply --auto-approve

      - name: build docker image
        run: docker build -t valid_password .
      - name: run docker image
        run: docker run valid_password
      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mahelnn/projettestcidockermain
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
