name: CI

on: [push]

env:
  AWS_DEFAULT_REGION: us-east-1
  
jobs:
  test_build_run_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        run: |
          # sudo snap install terraform -y
          terraform --version
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_PASSWORD }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_USERNAME }}
      - name: run main.tf
        run: |
          terraform init 
          terraform apply -var="AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID"  -var="AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY"   --auto-approve

      - name: build docker image
        run: docker build -t first-server .
      - name: run docker image
        run: docker run first-server
      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mahelnn/projettestcidockermain
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
